jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - continue-on-error: true
      uses: codecov/codecov-action@v1
      with:
        file: ./**/target/site/jacoco/jacoco.xml
        name: codecov
    strategy:
      matrix:
        java:
        - '8'
        - '11'
        - '17'
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
      }}
    needs: build
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: metadata
      name: Dependabot metadata
      uses: dependabot/fetch-metadata@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PR_URL: ${{github.event.pull_request.html_url}}
      if: ${{!contains(steps.metadata.outputs.dependency-names, 'maven-plugin-api')
        && (steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
        steps.metadata.outputs.update-type == 'version-update:semver-patch')}}
      name: Enable auto-merge for Dependabot PRs
      run: gh pr merge --auto --rebase "$PR_URL"
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
